spring:
  mybatis:
    typeAliasesPackage: com.example.demo.entity
    mapperLocations: classpath:**/*.xml
  datasource:
#    url: jdbc:mysql://10.24.13.223:3306/APIPlatform
    url: jdbc:mysql://localhost:3306/APIPlatform
    username: root
    password: lxh960119
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10Mb
    tomcat:
      uri-encoding: UTF-8
  http:
    multipart:
      max-request-size: 100Mb
    encoding:
      force: true
      charset: UTF-8
      enabled: true
